name: umi_0524_pointcloud

task_name: ${name}

shape_meta: &shape_meta
  obs:
    point_cloud:
      shape: [1024, 3]
      type: point_cloud
    agent_pos:
      shape: [7]
      type: low_dim
  action:
    shape: [7]

env_runner: null

dataset:
  _target_: diffusion_policies.dataset.panda_dataset.PandaDataset
  zarr_path: /nvme1/xinhai/projects/UMI-Gen/data/zarr/dataset_0524_vive_rsrgb_input/dp3_pointcloud.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: ${training.seed}
  val_ratio: 0.02
  max_train_episodes: null
